from child.Child import Child

children = {}

case_properties_Bob = {'Child plays in meaningful manner': True,
                       'Child can use intonation patterns similar to adults {}': False,
                       'Child tries to imitate adults {}': True,
                       'Child can use sounds to take its turn {}': True,
                       'Child waits for its own turn': False,
                       'Child can use 2 different vowels? {}': True,
                       'Child vocalizes interactively and makes use of voice inflections as well as objects during interaction {}': True,
                       'Child can answer many questions{}': False,
                       'Child plays with ball by pushing it back': True,
                       'Child tries to grab piece of toy outside arm reach{}': True,
                       'Child helps with simple domestic work': True,
                       'Child smiles or makes noice after talking {}': True,
                       'Child uses adult-like intonation {}': False,
                       'Child joins with playing kiekeboe': True,
                       'Child plays with hands and clothes{}': True,
                       'Child can talk about experiences {}': False,
                       'Child takes turn in conversations {}': False,
                       'Child plays next to other children and is in contact with them': False,
                       'Child is quiet after picking up {}': True,
                       'Child tries to sing along with songs {}': False,
                       'Child keeps to the rules of a game under guidance': False,
                       'Child uses consistent words for leaving/arriving/greeting and is able to describe movements with >2words {}': False,
                       'Child stays within clear rules of parents': False,
                       'Child makes choices if asked': False,
                       'Child does simple domestic work tasks': False,
                       'Child uses adult intonation pattern including questions and exclamations  {}': True,
                       'Child is a good imitator and repeats words of adults {}': False,
                       'Child brings toy/object to mouth {}': True,
                       'Child can say a child rhyme{}': False,
                       'Child combines vowels and consonants to make ba/da structures {}': True,
                       'Child says please if reminded': False,
                       'Child defends own toys': True,
                       'Child smiles spontaneously {}': True,
                       'Child plays simple games together': True,
                       'Child brabbles {}': True,
                       'Child can imitate movements and sounds {}': True,
                       'Child listens to music/story for 10min': False,
                       'Child waits for its turn with other children': False,
                       "Child uses words for persons, objects, animals and 'no' {}": False,
                       'Child joins with songs/rhymes': False,
                       'Child screams for attention and protests if by loud noise or crying something  happens that he/she dislikes {}': True,
                       'Child smiles at mirror image{}': True,
                       'Child turns image/book with correct side up to itself': True,
                       'Child uses repeatable 2-syllable structures baba/dada {}': True,
                       'Child can imitate face movements in combination with sounds {}': True,
                       'Child helps with putting on simple clothes': True,
                       'Child makes soft noise upon talking {}': True,
                       'Child expects to be lifted by i.e. moving limbs {}': True,
                       "Child can make at least 4 different sounds' {}": True,
                       'Child avoids danger': True,
                       'Child can vocalize without crying? {}': True,
                       'Child smiles and vocalizes when meeting a faimliar person {}': True,
                       'Child can use 3 word-sentences {}': False,
                       "Child tries to imitate 'talking' {}": True,
                       'Child can laugh out loud {}': True,
                       'Child knows own gender and can name it': False,
                       'Child reacts in (semi) words to simple questions  {}': True,
                       'Can follow orders {} percent of time': 40,
                       'Child can whisper and scream {}': True,
                       'Child plays with feet': True,
                       'Child vocalizes in different ways {}': True,
                       'Child plays with dolls': False,
                       'Child shows toy to adult': True,
                       'Child looks at other children playing': True,
                       'Child reacts on presence strangers by staring/crying': True,
                       'Child can sing simple songs {}': False,
                       'Child can share attention of parents': True,
                       'Child looks shortly at face {}': True,
                       'Child can say goodbye to parents without crying': False,
                       "Child asks w'questions like where, what {}": False,
                       'Child plays with different sorts of toys for 10min': False,
                       'Child can use 3 different vowels? {}': True,
                       'Child can say its full name {}': False,
                       'Child smiles at familiar game ': True,
                       'Child can repeat a 6 word sentence {}': False,
                       'Can speak {} words': 3, 'Child starts to undertand basic grammar {}': False,
                       'Child smiles if piece of cloth is put on head ': True,
                       'Child reacts with body movements upon talking {}': True, 'Can speak {} different vowels': 6,
                       'Child says half of the time please and thankyou without reminder': False,
                       'Child can imitate two-word-sentences {}': False,
                       'Child can communicate with friends with signs': True,
                       'Child plays simple functional games': True,
                       "Child's speech is understandable for at least 2/3 of time {}": False,
                       'Child imitates domestic work': True, "Child often throws with toy if it doesn't want it": False,
                       'Child can vocalize? {}': True,
                       'Child plays 15-20min alone without adult': False,
                       'Child tries shows off to get attention of parents': True,
                       'Child recognizes drinking bottle {}': True,
                       'Child can use one vowel {}': True,
                       'Child uses consistent same sounds for leaving/arriving {}': True,
                       'Child reacts at noise {}': True,
                       'Child looks at face for a while {}': True,
                       'Child has interest in surrounding {}': True,
                       'Child searches with eyes where sound is coming from {}': True,
                       'Child turns in movement of sound/voice {}': True,
                       'Child sits quiet in chair and has attention for object {}': True,
                       'Child can look at image for 2 minutes {}': True,
                       'Child changes facial expression in reaction to mad/friendly voices {}': True,
                       'Child listens to 1 talking person in noisy environment{}': True,
                       'Child listens to short story {}': True,
                       'Child listens to 10-min story {}': False,
                       'Child answers during story simple questions {}': False}

example_child = Child('Bob', case=case_properties_Bob)
children['Bob'] = example_child

case_properties_Lisa = {'Child plays in meaningful manner': True,
                   'Child can use intonation patterns similar to adults {}': True,
                   'Child tries to imitate adults {}': True,
                   'Child can use sounds to take its turn {}': True,
                   'Child waits for its own turn': True,
                   'Child can use 2 different vowels? {}': True,
                   'Child vocalizes interactively and makes use of voice inflections as well as objects during interaction {}': True,
                   'Child can answer many questions{}': True,
                   'Child plays with ball by pushing it back': True,
                   'Child tries to grab piece of toy outside arm reach{}': True,
                   'Child helps with simple domestic work': True,
                   'Child smiles or makes noice after talking {}': True,
                   'Child uses adult-like intonation {}': True,
                   'Child joins with playing kiekeboe': True,
                   'Child plays with hands and clothes{}': True,
                   'Child can talk about experiences {}': True,
                   'Child takes turn in conversations {}': True,
                   'Child plays next to other children and is in contact with them': True,
                   'Child is quiet after picking up {}': True,
                   'Child tries to sing along with songs {}': True,
                   'Child keeps to the rules of a game under guidance': True,
                   'Child uses consistent words for leaving/arriving/greeting and is able to describe movements with >2words {}': True,
                   'Child stays within clear rules of parents': True,
                   'Child makes choices if asked': True,
                   'Child does simple domestic work tasks': True,
                   'Child uses adult intonation pattern including questions and exclamations  {}': True,
                   'Child is a good imitator and repeats words of adults {}': True,
                   'Child brings toy/object to mouth {}': True,
                   'Child can say a child rhyme{}': True,
                   'Child combines vowels and consonants to make ba/da structures {}': True,
                   'Child says please if reminded': True,
                   'Child defends own toys': True,
                   'Child smiles spontaneously {}': True,
                   'Child plays simple games together': True,
                   'Child brabbles {}': True,
                   'Child can imitate movements and sounds {}': True,
                   'Child listens to music/story for 10min': True,
                   'Child waits for its turn with other children': True,
                   "Child uses words for persons, objects, animals and 'no' {}": True,
                   'Child joins with songs/rhymes': True,
                   'Child screams for attention and protests if by loud noise or crying something  happens that he/she dislikes {}': True,
                   'Child smiles at mirror image{}': True,
                   'Child turns image/book with correct side up to itself': True,
                   'Child uses repeatable 2-syllable structures baba/dada {}': True,
                   'Child can imitate face movements in combination with sounds {}': True,
                   'Child helps with putting on simple clothes': True,
                   'Child makes soft noise upon talking {}': True,
                   'Child expects to be lifted by i.e. moving limbs {}': True,
                   "Child can make at least 4 different sounds' {}": True,
                   'Child avoids danger': True,
                   'Child can vocalize without crying? {}': True,
                   'Child smiles and vocalizes when meeting a faimliar person {}': True,
                   'Child can use 3 word-sentences {}': True,
                   "Child tries to imitate 'talking' {}": True,
                   'Child can laugh out loud {}': True,
                   'Child knows own gender and can name it': True,
                   'Child reacts in (semi) words to simple questions  {}': True,
                   'Can follow orders {} percent of time': 50,
                   'Child can whisper and scream {}': True,
                   'Child plays with feet': True,
                   'Child vocalizes in different ways {}': True,
                   'Child plays with dolls': True,
                   'Child shows toy to adult': True,
                   'Child looks at other children playing': True,
                   'Child reacts on presence strangers by staring/crying': True,
                   'Child can sing simple songs {}': True,
                   'Child can share attention of parents': True,
                   'Child looks shortly at face {}': True,
                   'Child can say goodbye to parents without crying': True,
                   "Child asks w'questions like where, what {}": True,
                   'Child plays with different sorts of toys for 10min': True,
                   'Child can use 3 different vowels? {}': True,
                   'Child can say its full name {}': True,
                   'Child smiles at familiar game ': True,
                   'Child can repeat a 6 word sentence {}': True,
                   'Can speak {} words': 10, 'Child starts to undertand basic grammar {}': True,
                   'Child smiles if piece of cloth is put on head ': True,
                   'Child reacts with body movements upon talking {}': True,
                   'Child says half of the time please and thankyou without reminder': True,
                   'Child can imitate two-word-sentences {}': True,
                   'Child can communicate with friends with signs': True,
                   'Child plays simple functional games': True,
                   "Child's speech is understandable for at least 2/3 of time {}": True,
                   'Child imitates domestic work': True, "Child often throws with toy if it doesn't want it": True,
                   'Child can vocalize? {}': True,
                   'Child plays 15-20min alone without adult': True,
                   'Child tries shows off to get attention of parents': True,
                   'Child recognizes drinking bottle {}': True,
                   'Child can use one vowel {}': True,
                   'Child uses consistent same sounds for leaving/arriving {}': True}


def example_child(child):
    if child in children:
        return children[child]
    else:
        print("I don't know this kid!")
        print("I know these children")
        for k in children:
            print("\t {}".format(k))
